# Basic
Args = -H:+StackTrace -H:-OmitInlinedMethodDebugLineInfo --no-fallback
# with fast build time for dev
# Args = -H:+StackTrace -H:-OmitInlinedMethodDebugLineInfo --no-fallback -0b
# Debug
# Args = -H:+StackTrace -H:-OmitInlinedMethodDebugLineInfo -g --no-fallback
# Trying to find forbidden calls
# Args = -H:+StackTrace \
#        --no-fallback \
#        -H:TraceClassInitialization=* \
#        -H:ReportAnalysisForbiddenType=* \
#        --initialize-at-build-time=org.slf4j,org.apache.log4j,org.crosswire,org.stepbible.wasm.Bridge \
#        -H:+ReportExceptionStackTraces \
#        -H:+UnlockExperimentalVMOptions
